### PR TITLE
Rename LICENCE to LICENSE

### PR DESCRIPTION
**Pull request by 360disrupt**
http://grammarist.com/spelling/licence-license/ , with the previous file name the license checker does not find the license.

### CODE REVIEW

**Comment by dominictarr** [comment]
it's correct british english... unless you want to file lots of PRs like this one, you should just fix it in the licence checker.

**Comment by 360disrupt** [comment]
Actually, only your packages +1 more had that issue on my quite large package list. I could fix it in the license checker but I think other license programs have the same search logic, because github names the license file by default LICENSE not LICENCE because it is US based. Its not so much about a typo or not, more about standards.

**Comment by dominictarr** [comment]
You are asking me to fix something 4 times you can fix once. There are probably other occurances where you'll have to ask someone else to fix it again. Easier for everyone if you just fix it once.

Also, there are other licence checkers that already support "LICENCE" so maybe the standard _is both_.

I'm not gonna merge these, and in general, I won't merge one-off fixes if it can be once-and-for-all in just once place.

**Comment by govpack** [comment]
at this point it would be advisable to to drop all licences, 
especially the el-softo open source ones 
which don't mean anything anyway, to el-pinko hobbyist programmers 
lest anyone else become further incensed by the continental spelling police
also, i think it's best to file lots of pull requests 
to further highlight what pullers, or pull requesters you are

**Comment by 360disrupt** [comment]
I'm sorry that you seem to be so insulted by that request. I filled about 5 PR for that and I don't get any advantage of that. And yeah it is a dull PR without any huge benefits, but does it matter?

I will suggest to consider LICENSE at the licence checker to be accepted. I just notified you because I think it may not be the only package which may have problems with the British spelling. And people could name everything like they want, but the purpose of standards is that it is easier for others to build something on top of them.

**Comment by dominictarr** [comment]
It's not so much these 4 PRs, but it's that I have written _hundreds_ of modules, I have no idea how many have this spelling. So I could merge this, but then there will be others...

This actually happened before, and we fixed the checker!
https://github.com/dominictarr/event-stream/pull/69

**Pull request closed without merging**
