### PR TITLE
Clarify licensing

### PR DESCRIPTION
**Pull request by gdw2**
This is an attempt to make the license of this library detectable by the license-checker tool.

### CODE REVIEW

**Comment by cbas** [comment]
Would be nice to set the package.json license property so this package will have a valid SPDX license identifier. @dominictarr Any chance of merging this PR?

**Comment by dominictarr** [comment]
is merging this still necessary now that license-checker allows british spelling?

**Comment by cbas** [comment]
I don't think the International English `licence` spelling is supported by npm in `package.json`, though `npm publish` has a fallback to upload `LICENCE`.

https://docs.npmjs.com/files/package.json#files
> Certain files are always included, regardless of settings:
> 
> `package.json`
> - `README` (and its variants)
> - `CHANGELOG` (and its variants)
> - `LICENSE` / `LICENCE`

Adding an SPDX license identifier clears it up for spec-compliant tools (like many of the dependents of [spdx](https://www.npmjs.com/package/spdx)).

https://docs.npmjs.com/files/package.json#license
> If you're using a common license such as BSD-2-Clause or MIT, add a current SPDX license identifier for the license you're using, like this:
> 
>     { "license" : "BSD-3-Clause" }

I don't see any downsides to having the package.json license property.

**Comment by dominictarr** [comment]
merged into 3.3.2

**Pull request merged**
